name: tp0
services:
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./server/config.ini:/config.ini
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-1.csv:/dataset/agency-1.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server

  client2:
    container_name: client2
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-2.csv:/dataset/agency-2.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=2
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Luciana Maria
      - APELLIDO=Gomez
      - DOCUMENTO=32567892
      - NACIMIENTO=2000-07-21
      - NUMERO=8632
    networks:
      - testing_net
    depends_on:
      - server

  client3:
    container_name: client3
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-3.csv:/dataset/agency-3.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=3
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Javier Martin
      - APELLIDO=Perez
      - DOCUMENTO=28456789
      - NACIMIENTO=1998-12-11
      - NUMERO=4839
    networks:
      - testing_net
    depends_on:
      - server

  client4:
    container_name: client4
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-4.csv:/dataset/agency-4.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=4
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Veronica Alejandra
      - APELLIDO=Sanchez
      - DOCUMENTO=30123456
      - NACIMIENTO=2001-05-09
      - NUMERO=5901
    networks:
      - testing_net
    depends_on:
      - server

  client5:
    container_name: client5
    image: client:latest
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/dataset/agency-5.csv:/dataset/agency-5.csv
    entrypoint: python3 /main.py
    environment:
      - CLI_ID=5
      - CLI_LOG_LEVEL=DEBUG
      - NOMBRE=Rodrigo Ignacio
      - APELLIDO=Torres
      - DOCUMENTO=31456789
      - NACIMIENTO=1997-11-25
      - NUMERO=2048
    networks:
      - testing_net
    depends_on:
      - server



networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
        